#!/usr/bin/env bash
#=========================================================================
# 05-synopsys-vcs-baglsim
#=========================================================================

# Stop on error and echo all commands

set -e
trap 'echo "CMD: $BASH_COMMAND"' DEBUG

# Determine RUNDIR and SRCDIR

RUNDIR="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"
SRCDIR="$(readlink -f $RUNDIR/../../../sim/build)"

cd $RUNDIR

# Run baglsim

rm -rf simv* run.log

vcs -sverilog -xprop=tmerge -override_timescale=1ns/1ps -top Top \
  +neg_tchk +sdfverbose \
  -sdf max:Top.DUT:../04-cadence-innovus-pnr/post-pnr.sdf \
  +define+CYCLE_TIME=0.700 \
  +define+VTB_INPUT_DELAY=0.025 \
  +define+VTB_OUTPUT_DELAY=0.025 \
  +define+VTB_DUMP_SAIF=waves.saif \
  +vcs+dumpvars+waves.vcd \
  +incdir+${SRCDIR} \
  ${ECE6745_STDCELLS}/stdcells.v \
  ${SRCDIR}/SortUnitStruct_random_tb.v \
  ../04-cadence-innovus-pnr/post-pnr.v | tee run.log

./simv | tee -a run.log

