#!/usr/bin/env bash
#=========================================================================
# 01-synopsys-vcs-rtlsim
#=========================================================================

# Stop on error and echo all commands

set -e
trap 'echo "CMD: $BASH_COMMAND"' DEBUG

# Determine RUNDIR and SRCDIR

RUNDIR="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"
SRCDIR="$(readlink -f $RUNDIR/../../../sim/build)"

cd $RUNDIR

# Run rtlsim

rm -rf simv* run.log

vcs -sverilog -xprop=tmerge -override_timescale=1ns/1ps -top Top \
  +vcs+dumpvars+waves.vcd \
  +incdir+${SRCDIR} \
  ${SRCDIR}/SortUnitStruct_random_tb.v \
  ${SRCDIR}/SortUnitStruct__pickled.v | tee run.log

./simv | tee -a run.log

