#!/usr/bin/env bash
#=========================================================================
# 06-synopsys-pt-pwr
#=========================================================================

# Stop on error and echo all commands

set -e
trap 'echo "CMD: $BASH_COMMAND"' DEBUG

# Determine RUNDIR

RUNDIR="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"

cd $RUNDIR

# Run using run.tcl script

pt_shell -f run.tcl | tee run.log

